
  - name: hardening en servidores Ubuntu
    hosts: ubuntu
    become: yes
    tasks:
      - name: habilitar UFW y bloquear todo el trafico entrante
        community.general.ufw:
          state: enabled
          policy: deny
          direction: incoming

      - name: permitir solo SSH
        ufw:
          rule: allow
          name: OpenSSH

      - name: asegurar clave publica del usuario sysadmin
        ansible.posix.authorized_key: 
          user: sysadmin
          state: present
          key: "{{ lookup('file', 'keys/sysadmin.pub') }}"

      - name: habilitar autenticacion solo con clave publica
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication no'
          state: present

      - name: habiltiar autenticacion con clave publica
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PubkeyAuthentication'
          line: 'PubkeyAuthentication yes'
          state: present 
            
    handlers:
      - name: Reiniciar SSH
        service:
          name: sshd
          state: restarted
        
